name: deploy

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    env:
      LARAVEL_PATH: '/var/www/laravel/gmcard'
      WWW_USER: 'www-data'
      WWW_HOME: '/var/www'

    steps:
      - name: Run laravel commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo cp -r /home/${{ secrets.USER }}/.ssh ${{ env.WWW_HOME }}/
            sudo chown -R ${{ env.WWW_USER }}: ${{ env.WWW_HOME }}/.ssh
            cd ${{ env.LARAVEL_PATH }}
            echo -e "\033[0;32m composer install \033[0m"
            sudo -u ${{ env.WWW_USER }} composer install
            echo -e "\033[0;32m npm install \033[0m"
            sudo -u ${{ env.WWW_USER }} npm install --cache ./.npm
            echo -e "\033[0;32m git reset \033[0m"
            sudo -u ${{ env.WWW_USER }} git reset --hard
            echo -e "\033[0;32m git remote set-url \033[0m"
            sudo -u ${{ env.WWW_USER }} git remote set-url origin git@github.com:semelyanov86/gmcard.git
            echo -e "\033[0;32m task predeploy \033[0m"
            sudo -u ${{ env.WWW_USER }} task predeploy
            if [[ $? != 0 ]]; then exit 1; fi
            echo -e "\033[0;32m npm run build \033[0m"
            sudo -u ${{ env.WWW_USER }} npm run build
            if [[ $? != 0 ]]; then exit 1; fi
            echo -e "\033[0;32m php artisan ... \033[0m"
            sudo -u ${{ env.WWW_USER }} php artisan queue:restart
            sudo -u ${{ env.WWW_USER }} php artisan octane:reload
            echo -e "\033[0;32m remove \033[0m"
            sudo rm -rf ${{ env.WWW_HOME }}/.ssh

